
# data index of the file, at 2022/10
def index_data_previous():
    param_d = {
            "time"                  : "日付/時間",
            "MF1-CO2 flow"          : "CH1",  
            "MF2-Water1"            : "CH2",  
            "MF3-Water2"            : "CH3",  
            "PS1-compressor inlet"  : "CH6",
            "PS2-compressor outlet" : "CH7",
            "PS3-tank1 comp"        : "CH8",
            "PS4-tank1 expV"        : "CH9",
            "PS5-tank2 expV"        : "CH10",
            "PS6-tank2 comp"        : "CH11",
            "PS7-WHX1 comp"         : "CH12",
            "PS8-WHX1 expV"         : "CH13",
            "PS9-WHX2 expV"         : "CH14",
            "PS10-WHX2 comp"        : "CH15",
            "T-room"                : "CH20",
            "T1-compressor inlet"   : "CH21",
            "T2-compressor outlet"  : "CH22",
            "T3-tank1 comp"         : "CH23",
            "T4-tank1 expV"         : "CH24",
            "T5-tank2 expV"         : "CH25",
            "T6-tank2 comp"         : "CH26",
            "T7-WHX1 comp"          : "CH27",
            "T8-WHX1 expV"          : "CH28",
            "T9-WHX2 expV"          : "CH29",
            "T10-WHX2 comp"         : "CH30",
            "T11-tank1 water inlet" : "CH31",
            "T12-tank1 water outlet": "CH32",
            "T13-tank2 water inlet" : "CH33",
            "T14-tank2 water outlet": "CH34",
            "T21-tank1 mof"         : "CH35",
            "T22-tank1 mof"         : "CH36",
            "T23-tank1 mof"         : "CH37",
            "T24-tank1 mof"         : "CH38",
    }
    return param_d


    # data index of the file, after 2022/11
def index_data():
    param_d = {
            "time"                  : "日付/時間",
            "MF1-CO2 flow"          : "CH1",  
            "MF2-Water1"            : "CH2",  
            "MF3-Water2"            : "CH3",  
            "PS1-compressor inlet"  : "CH6",
            "PS2-compressor outlet" : "CH7",
            "PS3-tank1 comp"        : "CH8",
            "PS4-tank1 expV"        : "CH9",
            "PS5-tank2 expV"        : "CH10",
            "PS6-tank2 comp"        : "CH11",
            "PS7-WHX1 comp"         : "CH12",
            "PS8-WHX1 expV"         : "CH13",
            "PS9-WHX2 expV"         : "CH14",
            "PS10-WHX2 comp"        : "CH15",
            "T-room"                : "CH20",
            "T1-compressor inlet"   : "CH21",
            "T2-compressor outlet"  : "CH22",
            "T3-tank1 comp"         : "CH23",
            "T4-tank1 expV"         : "CH24",
            "T5-tank2 expV"         : "CH25",
            "T6-tank2 comp"         : "CH26",
            "T7-WHX1 comp"          : "CH27",
            "T8-WHX1 expV"          : "CH28",
            "T9-WHX2 expV"          : "CH29",
            "T10-WHX2 comp"         : "CH30",
            "T11-tank1 water inlet" : "CH41",
            "T12-tank1 water outlet": "CH42",
            "T13-tank2 water inlet" : "CH43",
            "T14-tank2 water outlet": "CH44",
            "T21-tank1 mof"         : "CH45",
            "T22-tank1 mof"         : "CH46",
            "T23-tank1 mof"         : "CH47",
            "T24-tank1 mof"         : "CH48",
            "T25-tank2 mof"         : "CH49",
            "T26-tank2 mof"         : "CH50",
            "T27-tank2 mof"         : "CH51",
            "T28-tank2 mof"         : "CH52",
            "T29-tank1 gas"         : "CH53",
            "T30-tank2 gas"         : "CH54",
    }
    return param_d